### ISSUE TITLE
Error (just installed it & tried to run it for the first time)

### ISSUE THREAD

**Issue by jromero2k** [bawaviki/SaveTube#1]
```bash
$ savetube
Traceback (most recent call last):
  File "/usr/local/bin/savetube", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/Savetube/__main__.py", line 181, in main
    app = App(root)
  File "/usr/local/lib/python3.7/site-packages/Savetube/GUI/__main__.py", line 119, in __init__
    self.icon = PhotoImage(file=os.path.dirname(os.path.abspath(__file__))+"/icon.png")
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 3545, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 3501, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "/usr/local/lib/python3.7/site-packages/Savetube/GUI/icon.png"
```

**Comment by bawaviki** [comment]
Check whether PIL is installed on your system or not. If not you easily installed PIL with `pip install Pillow`.

**Comment by jromero2k** [comment]
> Check whether PIL is installed on your system or not. If not you easily installed PIL with `pip install Pillow`.

```
Requirement already up-to-date: Pillow in /usr/local/lib/python3.7/site-packages (7.1.2)
```
